### ISSUE TITLE
LXC error PGP server validation 

### ISSUE THREAD

**Issue by oriolpiera** [coopdevs/devenv#41]
Seems that server https://sks-keyservers.net/ used to check PGP keys is down. So, when you create a LXC container, we get this error:

```
Loading project configuration from "/home/oriol/somenergia/src/odoo/odoo-somenergia-inventory/.devenv"
Loading system configuration from "/etc/devenv"
* CONFIGURATION:
  - Name: hr_employee_multidepartment
  - Distribution: ubuntu
  - Release: bionic
  - LXC Configuration: /tmp/ubuntu.hr_employee_multidepartment.conf
  - Hosts: hr_employee_multidepartment.local
  - Project Name: hr_employee_multidepartment
  - Project Directory: /home/oriol/somenergia/src/odoo/hr/hr_employee_multidepartment
  - Will mount on: /opt/odoo_modules/hr_employee_multidepartment
  - User: odoo
  - Group: odoo

Creating container hr_employee_multidepartment...
The cached copy has expired, re-downloading...
Setting up the GPG keyring
ERROR: Unable to fetch GPG key from keyserver
lxc-create: hr_employee_multidepartment: lxccontainer.c: create_run_template: 1617 Failed to create container from template
lxc-create: hr_employee_multidepartment: tools/lxc_create.c: main: 327 Failed to create container hr_employee_multidepartment
```

So, as a work arround, we add **--no-verify** param in lxc creation in devenv script line 160:

`  sudo lxc-create --name "$NAME" -f "$LXC_CONFIG" -t download -l INFO -- --dist "$DISTRIBUTION" --release "$RELEASE" --arch "$ARCH"
`
for 
`  sudo lxc-create --name "$NAME" -f "$LXC_CONFIG" -t download -l INFO -- --dist "$DISTRIBUTION" --release "$RELEASE" --arch "$ARCH" --no-validate
`

**Comment by rtertiaer** [comment]
This is fixed in [version 4.0.10 of lxc](https://discuss.linuxcontainers.org/t/lxc-4-0-10-has-been-released/11618) (ref: https://github.com/lxc/lxc/pull/3882.) In Debian, this is available in the "bookworm" (currently testing) release.

**Comment by enricostano** [comment]
I'm still seeing this issue with lxc version 4.0.11 on Arch Linux
